#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class client_conf:
  """
  Attributes:
   - msg_type
   - client_id
   - client_name
   - client_ip
   - client_port
   - match_type
   - camera_type
   - camera_ip
   - camera_port
   - camera_user
   - camera_pwd
   - card_type
   - face_no
   - threshold
   - match_ip
   - match_port
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'msg_type', None, None, ), # 1
    (2, TType.I32, 'client_id', None, None, ), # 2
    (3, TType.STRING, 'client_name', None, None, ), # 3
    (4, TType.STRING, 'client_ip', None, None, ), # 4
    (5, TType.I16, 'client_port', None, None, ), # 5
    (6, TType.BYTE, 'match_type', None, None, ), # 6
    (7, TType.BYTE, 'camera_type', None, None, ), # 7
    (8, TType.STRING, 'camera_ip', None, None, ), # 8
    (9, TType.I16, 'camera_port', None, None, ), # 9
    (10, TType.STRING, 'camera_user', None, None, ), # 10
    (11, TType.STRING, 'camera_pwd', None, None, ), # 11
    (12, TType.BYTE, 'card_type', None, None, ), # 12
    (13, TType.I16, 'face_no', None, None, ), # 13
    (14, TType.DOUBLE, 'threshold', None, None, ), # 14
    (15, TType.STRING, 'match_ip', None, None, ), # 15
    (16, TType.I16, 'match_port', None, None, ), # 16
  )

  def __init__(self, msg_type=None, client_id=None, client_name=None, client_ip=None, client_port=None, match_type=None, camera_type=None, camera_ip=None, camera_port=None, camera_user=None, camera_pwd=None, card_type=None, face_no=None, threshold=None, match_ip=None, match_port=None,):
    self.msg_type = msg_type
    self.client_id = client_id
    self.client_name = client_name
    self.client_ip = client_ip
    self.client_port = client_port
    self.match_type = match_type
    self.camera_type = camera_type
    self.camera_ip = camera_ip
    self.camera_port = camera_port
    self.camera_user = camera_user
    self.camera_pwd = camera_pwd
    self.card_type = card_type
    self.face_no = face_no
    self.threshold = threshold
    self.match_ip = match_ip
    self.match_port = match_port

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.msg_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.client_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.client_name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.client_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I16:
          self.client_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.BYTE:
          self.match_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.BYTE:
          self.camera_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.camera_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I16:
          self.camera_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.camera_user = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.camera_pwd = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.BYTE:
          self.card_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.I16:
          self.face_no = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.DOUBLE:
          self.threshold = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.STRING:
          self.match_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.I16:
          self.match_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('client_conf')
    if self.msg_type is not None:
      oprot.writeFieldBegin('msg_type', TType.BYTE, 1)
      oprot.writeByte(self.msg_type)
      oprot.writeFieldEnd()
    if self.client_id is not None:
      oprot.writeFieldBegin('client_id', TType.I32, 2)
      oprot.writeI32(self.client_id)
      oprot.writeFieldEnd()
    if self.client_name is not None:
      oprot.writeFieldBegin('client_name', TType.STRING, 3)
      oprot.writeString(self.client_name)
      oprot.writeFieldEnd()
    if self.client_ip is not None:
      oprot.writeFieldBegin('client_ip', TType.STRING, 4)
      oprot.writeString(self.client_ip)
      oprot.writeFieldEnd()
    if self.client_port is not None:
      oprot.writeFieldBegin('client_port', TType.I16, 5)
      oprot.writeI16(self.client_port)
      oprot.writeFieldEnd()
    if self.match_type is not None:
      oprot.writeFieldBegin('match_type', TType.BYTE, 6)
      oprot.writeByte(self.match_type)
      oprot.writeFieldEnd()
    if self.camera_type is not None:
      oprot.writeFieldBegin('camera_type', TType.BYTE, 7)
      oprot.writeByte(self.camera_type)
      oprot.writeFieldEnd()
    if self.camera_ip is not None:
      oprot.writeFieldBegin('camera_ip', TType.STRING, 8)
      oprot.writeString(self.camera_ip)
      oprot.writeFieldEnd()
    if self.camera_port is not None:
      oprot.writeFieldBegin('camera_port', TType.I16, 9)
      oprot.writeI16(self.camera_port)
      oprot.writeFieldEnd()
    if self.camera_user is not None:
      oprot.writeFieldBegin('camera_user', TType.STRING, 10)
      oprot.writeString(self.camera_user)
      oprot.writeFieldEnd()
    if self.camera_pwd is not None:
      oprot.writeFieldBegin('camera_pwd', TType.STRING, 11)
      oprot.writeString(self.camera_pwd)
      oprot.writeFieldEnd()
    if self.card_type is not None:
      oprot.writeFieldBegin('card_type', TType.BYTE, 12)
      oprot.writeByte(self.card_type)
      oprot.writeFieldEnd()
    if self.face_no is not None:
      oprot.writeFieldBegin('face_no', TType.I16, 13)
      oprot.writeI16(self.face_no)
      oprot.writeFieldEnd()
    if self.threshold is not None:
      oprot.writeFieldBegin('threshold', TType.DOUBLE, 14)
      oprot.writeDouble(self.threshold)
      oprot.writeFieldEnd()
    if self.match_ip is not None:
      oprot.writeFieldBegin('match_ip', TType.STRING, 15)
      oprot.writeString(self.match_ip)
      oprot.writeFieldEnd()
    if self.match_port is not None:
      oprot.writeFieldBegin('match_port', TType.I16, 16)
      oprot.writeI16(self.match_port)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.msg_type)
    value = (value * 31) ^ hash(self.client_id)
    value = (value * 31) ^ hash(self.client_name)
    value = (value * 31) ^ hash(self.client_ip)
    value = (value * 31) ^ hash(self.client_port)
    value = (value * 31) ^ hash(self.match_type)
    value = (value * 31) ^ hash(self.camera_type)
    value = (value * 31) ^ hash(self.camera_ip)
    value = (value * 31) ^ hash(self.camera_port)
    value = (value * 31) ^ hash(self.camera_user)
    value = (value * 31) ^ hash(self.camera_pwd)
    value = (value * 31) ^ hash(self.card_type)
    value = (value * 31) ^ hash(self.face_no)
    value = (value * 31) ^ hash(self.threshold)
    value = (value * 31) ^ hash(self.match_ip)
    value = (value * 31) ^ hash(self.match_port)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class SearchPicInfo:
  """
  Attributes:
   - p_id
   - face_db
   - score
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'p_id', None, None, ), # 1
    (2, TType.I32, 'face_db', None, None, ), # 2
    (3, TType.DOUBLE, 'score', None, None, ), # 3
  )

  def __init__(self, p_id=None, face_db=None, score=None,):
    self.p_id = p_id
    self.face_db = face_db
    self.score = score

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.p_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.face_db = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.DOUBLE:
          self.score = iprot.readDouble();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('SearchPicInfo')
    if self.p_id is not None:
      oprot.writeFieldBegin('p_id', TType.I32, 1)
      oprot.writeI32(self.p_id)
      oprot.writeFieldEnd()
    if self.face_db is not None:
      oprot.writeFieldBegin('face_db', TType.I32, 2)
      oprot.writeI32(self.face_db)
      oprot.writeFieldEnd()
    if self.score is not None:
      oprot.writeFieldBegin('score', TType.DOUBLE, 3)
      oprot.writeDouble(self.score)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.p_id)
    value = (value * 31) ^ hash(self.face_db)
    value = (value * 31) ^ hash(self.score)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class ClientInMsgPicSearch:
  """
  Attributes:
   - uuid
   - pic
   - face_no
   - threshold
   - pic_num
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'uuid', None, None, ), # 1
    (2, TType.STRING, 'pic', None, None, ), # 2
    (3, TType.I32, 'face_no', None, None, ), # 3
    (4, TType.DOUBLE, 'threshold', None, None, ), # 4
    (5, TType.I32, 'pic_num', None, None, ), # 5
  )

  def __init__(self, uuid=None, pic=None, face_no=None, threshold=None, pic_num=None,):
    self.uuid = uuid
    self.pic = pic
    self.face_no = face_no
    self.threshold = threshold
    self.pic_num = pic_num

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.uuid = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.pic = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.face_no = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.DOUBLE:
          self.threshold = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.pic_num = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ClientInMsgPicSearch')
    if self.uuid is not None:
      oprot.writeFieldBegin('uuid', TType.STRING, 1)
      oprot.writeString(self.uuid)
      oprot.writeFieldEnd()
    if self.pic is not None:
      oprot.writeFieldBegin('pic', TType.STRING, 2)
      oprot.writeString(self.pic)
      oprot.writeFieldEnd()
    if self.face_no is not None:
      oprot.writeFieldBegin('face_no', TType.I32, 3)
      oprot.writeI32(self.face_no)
      oprot.writeFieldEnd()
    if self.threshold is not None:
      oprot.writeFieldBegin('threshold', TType.DOUBLE, 4)
      oprot.writeDouble(self.threshold)
      oprot.writeFieldEnd()
    if self.pic_num is not None:
      oprot.writeFieldBegin('pic_num', TType.I32, 5)
      oprot.writeI32(self.pic_num)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uuid)
    value = (value * 31) ^ hash(self.pic)
    value = (value * 31) ^ hash(self.face_no)
    value = (value * 31) ^ hash(self.threshold)
    value = (value * 31) ^ hash(self.pic_num)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PicSerchReturn:
  """
  Attributes:
   - info
   - success_flag
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'info', (TType.STRUCT,(SearchPicInfo, SearchPicInfo.thrift_spec)), None, ), # 1
    (2, TType.I32, 'success_flag', None, None, ), # 2
  )

  def __init__(self, info=None, success_flag=None,):
    self.info = info
    self.success_flag = success_flag

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.info = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in range(_size0):
            _elem5 = SearchPicInfo()
            _elem5.read(iprot)
            self.info.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PicSerchReturn')
    if self.info is not None:
      oprot.writeFieldBegin('info', TType.LIST, 1)
      oprot.writeListBegin(TType.STRUCT, len(self.info))
      for iter6 in self.info:
        iter6.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 2)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.info)
    value = (value * 31) ^ hash(self.success_flag)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class SearchGrabPicInfo:
  """
  Attributes:
   - grab_id
   - c_id
   - score
   - time
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'grab_id', None, None, ), # 1
    (2, TType.I32, 'c_id', None, None, ), # 2
    (3, TType.DOUBLE, 'score', None, None, ), # 3
    (4, TType.STRING, 'time', None, None, ), # 4
  )

  def __init__(self, grab_id=None, c_id=None, score=None, time=None,):
    self.grab_id = grab_id
    self.c_id = c_id
    self.score = score
    self.time = time

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.grab_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.c_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.DOUBLE:
          self.score = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.time = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('SearchGrabPicInfo')
    if self.grab_id is not None:
      oprot.writeFieldBegin('grab_id', TType.I32, 1)
      oprot.writeI32(self.grab_id)
      oprot.writeFieldEnd()
    if self.c_id is not None:
      oprot.writeFieldBegin('c_id', TType.I32, 2)
      oprot.writeI32(self.c_id)
      oprot.writeFieldEnd()
    if self.score is not None:
      oprot.writeFieldBegin('score', TType.DOUBLE, 3)
      oprot.writeDouble(self.score)
      oprot.writeFieldEnd()
    if self.time is not None:
      oprot.writeFieldBegin('time', TType.STRING, 4)
      oprot.writeString(self.time)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.grab_id)
    value = (value * 31) ^ hash(self.c_id)
    value = (value * 31) ^ hash(self.score)
    value = (value * 31) ^ hash(self.time)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PicSearchInGrab:
  """
  Attributes:
   - uuid
   - pic
   - c_id
   - time
   - score
   - pic_num
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'uuid', None, None, ), # 1
    (2, TType.STRING, 'pic', None, None, ), # 2
    (3, TType.LIST, 'c_id', (TType.I32,None), None, ), # 3
    (4, TType.LIST, 'time', (TType.STRING,None), None, ), # 4
    (5, TType.DOUBLE, 'score', None, None, ), # 5
    (6, TType.I32, 'pic_num', None, None, ), # 6
  )

  def __init__(self, uuid=None, pic=None, c_id=None, time=None, score=None, pic_num=None,):
    self.uuid = uuid
    self.pic = pic
    self.c_id = c_id
    self.time = time
    self.score = score
    self.pic_num = pic_num

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.uuid = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.pic = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.LIST:
          self.c_id = []
          (_etype10, _size7) = iprot.readListBegin()
          for _i11 in range(_size7):
            _elem12 = iprot.readI32();
            self.c_id.append(_elem12)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.time = []
          (_etype16, _size13) = iprot.readListBegin()
          for _i17 in range(_size13):
            _elem18 = iprot.readString();
            self.time.append(_elem18)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.DOUBLE:
          self.score = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.pic_num = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PicSearchInGrab')
    if self.uuid is not None:
      oprot.writeFieldBegin('uuid', TType.STRING, 1)
      oprot.writeString(self.uuid)
      oprot.writeFieldEnd()
    if self.pic is not None:
      oprot.writeFieldBegin('pic', TType.STRING, 2)
      oprot.writeString(self.pic)
      oprot.writeFieldEnd()
    if self.c_id is not None:
      oprot.writeFieldBegin('c_id', TType.LIST, 3)
      oprot.writeListBegin(TType.I32, len(self.c_id))
      for iter19 in self.c_id:
        oprot.writeI32(iter19)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.time is not None:
      oprot.writeFieldBegin('time', TType.LIST, 4)
      oprot.writeListBegin(TType.STRING, len(self.time))
      for iter20 in self.time:
        oprot.writeString(iter20)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.score is not None:
      oprot.writeFieldBegin('score', TType.DOUBLE, 5)
      oprot.writeDouble(self.score)
      oprot.writeFieldEnd()
    if self.pic_num is not None:
      oprot.writeFieldBegin('pic_num', TType.I32, 6)
      oprot.writeI32(self.pic_num)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uuid)
    value = (value * 31) ^ hash(self.pic)
    value = (value * 31) ^ hash(self.c_id)
    value = (value * 31) ^ hash(self.time)
    value = (value * 31) ^ hash(self.score)
    value = (value * 31) ^ hash(self.pic_num)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class GrabPicSearchReturn:
  """
  Attributes:
   - info
   - success_flag
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'info', (TType.STRUCT,(SearchGrabPicInfo, SearchGrabPicInfo.thrift_spec)), None, ), # 1
    (2, TType.I32, 'success_flag', None, None, ), # 2
  )

  def __init__(self, info=None, success_flag=None,):
    self.info = info
    self.success_flag = success_flag

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.info = []
          (_etype24, _size21) = iprot.readListBegin()
          for _i25 in range(_size21):
            _elem26 = SearchGrabPicInfo()
            _elem26.read(iprot)
            self.info.append(_elem26)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('GrabPicSearchReturn')
    if self.info is not None:
      oprot.writeFieldBegin('info', TType.LIST, 1)
      oprot.writeListBegin(TType.STRUCT, len(self.info))
      for iter27 in self.info:
        iter27.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 2)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.info)
    value = (value * 31) ^ hash(self.success_flag)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class GetPicFeatureAndSmallPicIn:
  """
  Attributes:
   - uuid
   - pic
   - pic_size
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'uuid', None, None, ), # 1
    (2, TType.STRING, 'pic', None, None, ), # 2
    (3, TType.I32, 'pic_size', None, None, ), # 3
  )

  def __init__(self, uuid=None, pic=None, pic_size=None,):
    self.uuid = uuid
    self.pic = pic
    self.pic_size = pic_size

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.uuid = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.pic = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.pic_size = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('GetPicFeatureAndSmallPicIn')
    if self.uuid is not None:
      oprot.writeFieldBegin('uuid', TType.STRING, 1)
      oprot.writeString(self.uuid)
      oprot.writeFieldEnd()
    if self.pic is not None:
      oprot.writeFieldBegin('pic', TType.STRING, 2)
      oprot.writeString(self.pic)
      oprot.writeFieldEnd()
    if self.pic_size is not None:
      oprot.writeFieldBegin('pic_size', TType.I32, 3)
      oprot.writeI32(self.pic_size)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uuid)
    value = (value * 31) ^ hash(self.pic)
    value = (value * 31) ^ hash(self.pic_size)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class GetPicFeatureAndSmallPicReturn:
  """
  Attributes:
   - uuid
   - pic
   - pic_size
   - feature
   - success_flag
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'uuid', None, None, ), # 1
    (2, TType.STRING, 'pic', None, None, ), # 2
    (3, TType.I32, 'pic_size', None, None, ), # 3
    (4, TType.STRING, 'feature', None, None, ), # 4
    (5, TType.I32, 'success_flag', None, None, ), # 5
  )

  def __init__(self, uuid=None, pic=None, pic_size=None, feature=None, success_flag=None,):
    self.uuid = uuid
    self.pic = pic
    self.pic_size = pic_size
    self.feature = feature
    self.success_flag = success_flag

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.uuid = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.pic = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.pic_size = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.feature = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('GetPicFeatureAndSmallPicReturn')
    if self.uuid is not None:
      oprot.writeFieldBegin('uuid', TType.STRING, 1)
      oprot.writeString(self.uuid)
      oprot.writeFieldEnd()
    if self.pic is not None:
      oprot.writeFieldBegin('pic', TType.STRING, 2)
      oprot.writeString(self.pic)
      oprot.writeFieldEnd()
    if self.pic_size is not None:
      oprot.writeFieldBegin('pic_size', TType.I32, 3)
      oprot.writeI32(self.pic_size)
      oprot.writeFieldEnd()
    if self.feature is not None:
      oprot.writeFieldBegin('feature', TType.STRING, 4)
      oprot.writeString(self.feature)
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 5)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uuid)
    value = (value * 31) ^ hash(self.pic)
    value = (value * 31) ^ hash(self.pic_size)
    value = (value * 31) ^ hash(self.feature)
    value = (value * 31) ^ hash(self.success_flag)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class alarm_conf:
  """
  Attributes:
   - alarm_id
   - alarm_ip
   - alarm_port
   - c_id_list
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'alarm_id', None, None, ), # 1
    (2, TType.STRING, 'alarm_ip', None, None, ), # 2
    (3, TType.I16, 'alarm_port', None, None, ), # 3
    (4, TType.LIST, 'c_id_list', (TType.I32,None), None, ), # 4
  )

  def __init__(self, alarm_id=None, alarm_ip=None, alarm_port=None, c_id_list=None,):
    self.alarm_id = alarm_id
    self.alarm_ip = alarm_ip
    self.alarm_port = alarm_port
    self.c_id_list = c_id_list

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.alarm_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.alarm_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I16:
          self.alarm_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.c_id_list = []
          (_etype31, _size28) = iprot.readListBegin()
          for _i32 in range(_size28):
            _elem33 = iprot.readI32();
            self.c_id_list.append(_elem33)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('alarm_conf')
    if self.alarm_id is not None:
      oprot.writeFieldBegin('alarm_id', TType.I32, 1)
      oprot.writeI32(self.alarm_id)
      oprot.writeFieldEnd()
    if self.alarm_ip is not None:
      oprot.writeFieldBegin('alarm_ip', TType.STRING, 2)
      oprot.writeString(self.alarm_ip)
      oprot.writeFieldEnd()
    if self.alarm_port is not None:
      oprot.writeFieldBegin('alarm_port', TType.I16, 3)
      oprot.writeI16(self.alarm_port)
      oprot.writeFieldEnd()
    if self.c_id_list is not None:
      oprot.writeFieldBegin('c_id_list', TType.LIST, 4)
      oprot.writeListBegin(TType.I32, len(self.c_id_list))
      for iter34 in self.c_id_list:
        oprot.writeI32(iter34)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.alarm_id)
    value = (value * 31) ^ hash(self.alarm_ip)
    value = (value * 31) ^ hash(self.alarm_port)
    value = (value * 31) ^ hash(self.c_id_list)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class match_conf:
  """
  Attributes:
   - msg_type
   - match_name
   - match_ip
   - match_port
   - face_no
   - threshold
   - clients_max
   - sql_addr
   - sql_port
   - sql_user
   - sql_pwd
   - match_result_table
   - grab_face_table
   - face_no_table
   - person_no
   - person_name
   - person_id
   - feature
   - face_pic
   - db_name
   - person_table
   - alarm_config_info
   - success_flag
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'msg_type', None, None, ), # 1
    (2, TType.STRING, 'match_name', None, None, ), # 2
    (3, TType.STRING, 'match_ip', None, None, ), # 3
    (4, TType.I16, 'match_port', None, None, ), # 4
    (5, TType.I16, 'face_no', None, None, ), # 5
    (6, TType.DOUBLE, 'threshold', None, None, ), # 6
    (7, TType.I32, 'clients_max', None, None, ), # 7
    (8, TType.STRING, 'sql_addr', None, None, ), # 8
    (9, TType.I16, 'sql_port', None, None, ), # 9
    (10, TType.STRING, 'sql_user', None, None, ), # 10
    (11, TType.STRING, 'sql_pwd', None, None, ), # 11
    (12, TType.STRING, 'match_result_table', None, None, ), # 12
    (13, TType.STRING, 'grab_face_table', None, None, ), # 13
    (14, TType.STRING, 'face_no_table', None, None, ), # 14
    (15, TType.I32, 'person_no', None, None, ), # 15
    (16, TType.STRING, 'person_name', None, None, ), # 16
    (17, TType.STRING, 'person_id', None, None, ), # 17
    (18, TType.STRING, 'feature', None, None, ), # 18
    (19, TType.STRING, 'face_pic', None, None, ), # 19
    (20, TType.STRING, 'db_name', None, None, ), # 20
    (21, TType.STRING, 'person_table', None, None, ), # 21
    (22, TType.LIST, 'alarm_config_info', (TType.STRUCT,(alarm_conf, alarm_conf.thrift_spec)), None, ), # 22
    (23, TType.I32, 'success_flag', None, None, ), # 23
  )

  def __init__(self, msg_type=None, match_name=None, match_ip=None, match_port=None, face_no=None, threshold=None, clients_max=None, sql_addr=None, sql_port=None, sql_user=None, sql_pwd=None, match_result_table=None, grab_face_table=None, face_no_table=None, person_no=None, person_name=None, person_id=None, feature=None, face_pic=None, db_name=None, person_table=None, alarm_config_info=None, success_flag=None,):
    self.msg_type = msg_type
    self.match_name = match_name
    self.match_ip = match_ip
    self.match_port = match_port
    self.face_no = face_no
    self.threshold = threshold
    self.clients_max = clients_max
    self.sql_addr = sql_addr
    self.sql_port = sql_port
    self.sql_user = sql_user
    self.sql_pwd = sql_pwd
    self.match_result_table = match_result_table
    self.grab_face_table = grab_face_table
    self.face_no_table = face_no_table
    self.person_no = person_no
    self.person_name = person_name
    self.person_id = person_id
    self.feature = feature
    self.face_pic = face_pic
    self.db_name = db_name
    self.person_table = person_table
    self.alarm_config_info = alarm_config_info
    self.success_flag = success_flag

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.msg_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.match_name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.match_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.match_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I16:
          self.face_no = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.DOUBLE:
          self.threshold = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.clients_max = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.sql_addr = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I16:
          self.sql_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.sql_user = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.sql_pwd = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.match_result_table = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.STRING:
          self.grab_face_table = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.STRING:
          self.face_no_table = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.I32:
          self.person_no = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.STRING:
          self.person_name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRING:
          self.person_id = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.STRING:
          self.feature = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 19:
        if ftype == TType.STRING:
          self.face_pic = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRING:
          self.db_name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 21:
        if ftype == TType.STRING:
          self.person_table = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 22:
        if ftype == TType.LIST:
          self.alarm_config_info = []
          (_etype38, _size35) = iprot.readListBegin()
          for _i39 in range(_size35):
            _elem40 = alarm_conf()
            _elem40.read(iprot)
            self.alarm_config_info.append(_elem40)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 23:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('match_conf')
    if self.msg_type is not None:
      oprot.writeFieldBegin('msg_type', TType.BYTE, 1)
      oprot.writeByte(self.msg_type)
      oprot.writeFieldEnd()
    if self.match_name is not None:
      oprot.writeFieldBegin('match_name', TType.STRING, 2)
      oprot.writeString(self.match_name)
      oprot.writeFieldEnd()
    if self.match_ip is not None:
      oprot.writeFieldBegin('match_ip', TType.STRING, 3)
      oprot.writeString(self.match_ip)
      oprot.writeFieldEnd()
    if self.match_port is not None:
      oprot.writeFieldBegin('match_port', TType.I16, 4)
      oprot.writeI16(self.match_port)
      oprot.writeFieldEnd()
    if self.face_no is not None:
      oprot.writeFieldBegin('face_no', TType.I16, 5)
      oprot.writeI16(self.face_no)
      oprot.writeFieldEnd()
    if self.threshold is not None:
      oprot.writeFieldBegin('threshold', TType.DOUBLE, 6)
      oprot.writeDouble(self.threshold)
      oprot.writeFieldEnd()
    if self.clients_max is not None:
      oprot.writeFieldBegin('clients_max', TType.I32, 7)
      oprot.writeI32(self.clients_max)
      oprot.writeFieldEnd()
    if self.sql_addr is not None:
      oprot.writeFieldBegin('sql_addr', TType.STRING, 8)
      oprot.writeString(self.sql_addr)
      oprot.writeFieldEnd()
    if self.sql_port is not None:
      oprot.writeFieldBegin('sql_port', TType.I16, 9)
      oprot.writeI16(self.sql_port)
      oprot.writeFieldEnd()
    if self.sql_user is not None:
      oprot.writeFieldBegin('sql_user', TType.STRING, 10)
      oprot.writeString(self.sql_user)
      oprot.writeFieldEnd()
    if self.sql_pwd is not None:
      oprot.writeFieldBegin('sql_pwd', TType.STRING, 11)
      oprot.writeString(self.sql_pwd)
      oprot.writeFieldEnd()
    if self.match_result_table is not None:
      oprot.writeFieldBegin('match_result_table', TType.STRING, 12)
      oprot.writeString(self.match_result_table)
      oprot.writeFieldEnd()
    if self.grab_face_table is not None:
      oprot.writeFieldBegin('grab_face_table', TType.STRING, 13)
      oprot.writeString(self.grab_face_table)
      oprot.writeFieldEnd()
    if self.face_no_table is not None:
      oprot.writeFieldBegin('face_no_table', TType.STRING, 14)
      oprot.writeString(self.face_no_table)
      oprot.writeFieldEnd()
    if self.person_no is not None:
      oprot.writeFieldBegin('person_no', TType.I32, 15)
      oprot.writeI32(self.person_no)
      oprot.writeFieldEnd()
    if self.person_name is not None:
      oprot.writeFieldBegin('person_name', TType.STRING, 16)
      oprot.writeString(self.person_name)
      oprot.writeFieldEnd()
    if self.person_id is not None:
      oprot.writeFieldBegin('person_id', TType.STRING, 17)
      oprot.writeString(self.person_id)
      oprot.writeFieldEnd()
    if self.feature is not None:
      oprot.writeFieldBegin('feature', TType.STRING, 18)
      oprot.writeString(self.feature)
      oprot.writeFieldEnd()
    if self.face_pic is not None:
      oprot.writeFieldBegin('face_pic', TType.STRING, 19)
      oprot.writeString(self.face_pic)
      oprot.writeFieldEnd()
    if self.db_name is not None:
      oprot.writeFieldBegin('db_name', TType.STRING, 20)
      oprot.writeString(self.db_name)
      oprot.writeFieldEnd()
    if self.person_table is not None:
      oprot.writeFieldBegin('person_table', TType.STRING, 21)
      oprot.writeString(self.person_table)
      oprot.writeFieldEnd()
    if self.alarm_config_info is not None:
      oprot.writeFieldBegin('alarm_config_info', TType.LIST, 22)
      oprot.writeListBegin(TType.STRUCT, len(self.alarm_config_info))
      for iter41 in self.alarm_config_info:
        iter41.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 23)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.msg_type)
    value = (value * 31) ^ hash(self.match_name)
    value = (value * 31) ^ hash(self.match_ip)
    value = (value * 31) ^ hash(self.match_port)
    value = (value * 31) ^ hash(self.face_no)
    value = (value * 31) ^ hash(self.threshold)
    value = (value * 31) ^ hash(self.clients_max)
    value = (value * 31) ^ hash(self.sql_addr)
    value = (value * 31) ^ hash(self.sql_port)
    value = (value * 31) ^ hash(self.sql_user)
    value = (value * 31) ^ hash(self.sql_pwd)
    value = (value * 31) ^ hash(self.match_result_table)
    value = (value * 31) ^ hash(self.grab_face_table)
    value = (value * 31) ^ hash(self.face_no_table)
    value = (value * 31) ^ hash(self.person_no)
    value = (value * 31) ^ hash(self.person_name)
    value = (value * 31) ^ hash(self.person_id)
    value = (value * 31) ^ hash(self.feature)
    value = (value * 31) ^ hash(self.face_pic)
    value = (value * 31) ^ hash(self.db_name)
    value = (value * 31) ^ hash(self.person_table)
    value = (value * 31) ^ hash(self.alarm_config_info)
    value = (value * 31) ^ hash(self.success_flag)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class net_video_in_conf:
  """
  Attributes:
   - ip
   - port
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'ip', None, None, ), # 1
    (2, TType.I32, 'port', None, None, ), # 2
  )

  def __init__(self, ip=None, port=None,):
    self.ip = ip
    self.port = port

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.port = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('net_video_in_conf')
    if self.ip is not None:
      oprot.writeFieldBegin('ip', TType.STRING, 1)
      oprot.writeString(self.ip)
      oprot.writeFieldEnd()
    if self.port is not None:
      oprot.writeFieldBegin('port', TType.I32, 2)
      oprot.writeI32(self.port)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.ip)
    value = (value * 31) ^ hash(self.port)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class net_video_channel:
  """
  Attributes:
   - device_id
   - channel_dev_id
   - channel_no
   - channel_name
   - connect_mode
   - face_db_no
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'device_id', None, None, ), # 1
    (2, TType.I32, 'channel_dev_id', None, None, ), # 2
    (3, TType.I32, 'channel_no', None, None, ), # 3
    (4, TType.STRING, 'channel_name', None, None, ), # 4
    (5, TType.I32, 'connect_mode', None, None, ), # 5
    (6, TType.LIST, 'face_db_no', (TType.I32,None), None, ), # 6
  )

  def __init__(self, device_id=None, channel_dev_id=None, channel_no=None, channel_name=None, connect_mode=None, face_db_no=None,):
    self.device_id = device_id
    self.channel_dev_id = channel_dev_id
    self.channel_no = channel_no
    self.channel_name = channel_name
    self.connect_mode = connect_mode
    self.face_db_no = face_db_no

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.device_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.channel_dev_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.channel_no = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.channel_name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.connect_mode = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.LIST:
          self.face_db_no = []
          (_etype45, _size42) = iprot.readListBegin()
          for _i46 in range(_size42):
            _elem47 = iprot.readI32();
            self.face_db_no.append(_elem47)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('net_video_channel')
    if self.device_id is not None:
      oprot.writeFieldBegin('device_id', TType.I32, 1)
      oprot.writeI32(self.device_id)
      oprot.writeFieldEnd()
    if self.channel_dev_id is not None:
      oprot.writeFieldBegin('channel_dev_id', TType.I32, 2)
      oprot.writeI32(self.channel_dev_id)
      oprot.writeFieldEnd()
    if self.channel_no is not None:
      oprot.writeFieldBegin('channel_no', TType.I32, 3)
      oprot.writeI32(self.channel_no)
      oprot.writeFieldEnd()
    if self.channel_name is not None:
      oprot.writeFieldBegin('channel_name', TType.STRING, 4)
      oprot.writeString(self.channel_name)
      oprot.writeFieldEnd()
    if self.connect_mode is not None:
      oprot.writeFieldBegin('connect_mode', TType.I32, 5)
      oprot.writeI32(self.connect_mode)
      oprot.writeFieldEnd()
    if self.face_db_no is not None:
      oprot.writeFieldBegin('face_db_no', TType.LIST, 6)
      oprot.writeListBegin(TType.I32, len(self.face_db_no))
      for iter48 in self.face_db_no:
        oprot.writeI32(iter48)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.device_id)
    value = (value * 31) ^ hash(self.channel_dev_id)
    value = (value * 31) ^ hash(self.channel_no)
    value = (value * 31) ^ hash(self.channel_name)
    value = (value * 31) ^ hash(self.connect_mode)
    value = (value * 31) ^ hash(self.face_db_no)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class net_video_host:
  """
  Attributes:
   - msg_type
   - type
   - device_id
   - ip
   - port
   - user
   - pwd
   - channels
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'msg_type', None, None, ), # 1
    (2, TType.I32, 'type', None, None, ), # 2
    (3, TType.I32, 'device_id', None, None, ), # 3
    (4, TType.STRING, 'ip', None, None, ), # 4
    (5, TType.I32, 'port', None, None, ), # 5
    (6, TType.STRING, 'user', None, None, ), # 6
    (7, TType.STRING, 'pwd', None, None, ), # 7
    (8, TType.LIST, 'channels', (TType.STRUCT,(net_video_channel, net_video_channel.thrift_spec)), None, ), # 8
  )

  def __init__(self, msg_type=None, type=None, device_id=None, ip=None, port=None, user=None, pwd=None, channels=None,):
    self.msg_type = msg_type
    self.type = type
    self.device_id = device_id
    self.ip = ip
    self.port = port
    self.user = user
    self.pwd = pwd
    self.channels = channels

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.msg_type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.device_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.port = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.user = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.pwd = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.LIST:
          self.channels = []
          (_etype52, _size49) = iprot.readListBegin()
          for _i53 in range(_size49):
            _elem54 = net_video_channel()
            _elem54.read(iprot)
            self.channels.append(_elem54)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('net_video_host')
    if self.msg_type is not None:
      oprot.writeFieldBegin('msg_type', TType.I32, 1)
      oprot.writeI32(self.msg_type)
      oprot.writeFieldEnd()
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.I32, 2)
      oprot.writeI32(self.type)
      oprot.writeFieldEnd()
    if self.device_id is not None:
      oprot.writeFieldBegin('device_id', TType.I32, 3)
      oprot.writeI32(self.device_id)
      oprot.writeFieldEnd()
    if self.ip is not None:
      oprot.writeFieldBegin('ip', TType.STRING, 4)
      oprot.writeString(self.ip)
      oprot.writeFieldEnd()
    if self.port is not None:
      oprot.writeFieldBegin('port', TType.I32, 5)
      oprot.writeI32(self.port)
      oprot.writeFieldEnd()
    if self.user is not None:
      oprot.writeFieldBegin('user', TType.STRING, 6)
      oprot.writeString(self.user)
      oprot.writeFieldEnd()
    if self.pwd is not None:
      oprot.writeFieldBegin('pwd', TType.STRING, 7)
      oprot.writeString(self.pwd)
      oprot.writeFieldEnd()
    if self.channels is not None:
      oprot.writeFieldBegin('channels', TType.LIST, 8)
      oprot.writeListBegin(TType.STRUCT, len(self.channels))
      for iter55 in self.channels:
        iter55.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.msg_type)
    value = (value * 31) ^ hash(self.type)
    value = (value * 31) ^ hash(self.device_id)
    value = (value * 31) ^ hash(self.ip)
    value = (value * 31) ^ hash(self.port)
    value = (value * 31) ^ hash(self.user)
    value = (value * 31) ^ hash(self.pwd)
    value = (value * 31) ^ hash(self.channels)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class net_video_conf:
  """
  Attributes:
   - hosts
   - match_ip
   - match_port
   - cap_interval
   - cap_type
   - success_flag
   - err_msg
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'hosts', (TType.STRUCT,(net_video_host, net_video_host.thrift_spec)), None, ), # 1
    (2, TType.STRING, 'match_ip', None, None, ), # 2
    (3, TType.I32, 'match_port', None, None, ), # 3
    (4, TType.I32, 'cap_interval', None, None, ), # 4
    (5, TType.I32, 'cap_type', None, None, ), # 5
    (6, TType.I32, 'success_flag', None, None, ), # 6
    (7, TType.STRING, 'err_msg', None, None, ), # 7
  )

  def __init__(self, hosts=None, match_ip=None, match_port=None, cap_interval=None, cap_type=None, success_flag=None, err_msg=None,):
    self.hosts = hosts
    self.match_ip = match_ip
    self.match_port = match_port
    self.cap_interval = cap_interval
    self.cap_type = cap_type
    self.success_flag = success_flag
    self.err_msg = err_msg

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.hosts = []
          (_etype59, _size56) = iprot.readListBegin()
          for _i60 in range(_size56):
            _elem61 = net_video_host()
            _elem61.read(iprot)
            self.hosts.append(_elem61)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.match_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.match_port = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.cap_interval = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.cap_type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.err_msg = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('net_video_conf')
    if self.hosts is not None:
      oprot.writeFieldBegin('hosts', TType.LIST, 1)
      oprot.writeListBegin(TType.STRUCT, len(self.hosts))
      for iter62 in self.hosts:
        iter62.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.match_ip is not None:
      oprot.writeFieldBegin('match_ip', TType.STRING, 2)
      oprot.writeString(self.match_ip)
      oprot.writeFieldEnd()
    if self.match_port is not None:
      oprot.writeFieldBegin('match_port', TType.I32, 3)
      oprot.writeI32(self.match_port)
      oprot.writeFieldEnd()
    if self.cap_interval is not None:
      oprot.writeFieldBegin('cap_interval', TType.I32, 4)
      oprot.writeI32(self.cap_interval)
      oprot.writeFieldEnd()
    if self.cap_type is not None:
      oprot.writeFieldBegin('cap_type', TType.I32, 5)
      oprot.writeI32(self.cap_type)
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 6)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    if self.err_msg is not None:
      oprot.writeFieldBegin('err_msg', TType.STRING, 7)
      oprot.writeString(self.err_msg)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.hosts)
    value = (value * 31) ^ hash(self.match_ip)
    value = (value * 31) ^ hash(self.match_port)
    value = (value * 31) ^ hash(self.cap_interval)
    value = (value * 31) ^ hash(self.cap_type)
    value = (value * 31) ^ hash(self.success_flag)
    value = (value * 31) ^ hash(self.err_msg)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class match_info:
  """
  Attributes:
   - msg_type
   - match_ip
   - match_port
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'msg_type', None, None, ), # 1
    (2, TType.STRING, 'match_ip', None, None, ), # 2
    (3, TType.I32, 'match_port', None, None, ), # 3
  )

  def __init__(self, msg_type=None, match_ip=None, match_port=None,):
    self.msg_type = msg_type
    self.match_ip = match_ip
    self.match_port = match_port

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.msg_type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.match_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.match_port = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('match_info')
    if self.msg_type is not None:
      oprot.writeFieldBegin('msg_type', TType.I32, 1)
      oprot.writeI32(self.msg_type)
      oprot.writeFieldEnd()
    if self.match_ip is not None:
      oprot.writeFieldBegin('match_ip', TType.STRING, 2)
      oprot.writeString(self.match_ip)
      oprot.writeFieldEnd()
    if self.match_port is not None:
      oprot.writeFieldBegin('match_port', TType.I32, 3)
      oprot.writeI32(self.match_port)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.msg_type)
    value = (value * 31) ^ hash(self.match_ip)
    value = (value * 31) ^ hash(self.match_port)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class alarm:
  """
  Attributes:
   - msg_type
   - alarm_id
   - alarm_ip
   - alarm_port
   - c_id_list
   - success_flag
  """

  thrift_spec = (
    None, # 0
    (1, TType.BYTE, 'msg_type', None, None, ), # 1
    (2, TType.I32, 'alarm_id', None, None, ), # 2
    (3, TType.STRING, 'alarm_ip', None, None, ), # 3
    (4, TType.I16, 'alarm_port', None, None, ), # 4
    (5, TType.LIST, 'c_id_list', (TType.I32,None), None, ), # 5
    (6, TType.I32, 'success_flag', None, None, ), # 6
  )

  def __init__(self, msg_type=None, alarm_id=None, alarm_ip=None, alarm_port=None, c_id_list=None, success_flag=None,):
    self.msg_type = msg_type
    self.alarm_id = alarm_id
    self.alarm_ip = alarm_ip
    self.alarm_port = alarm_port
    self.c_id_list = c_id_list
    self.success_flag = success_flag

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.BYTE:
          self.msg_type = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.alarm_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.alarm_ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.alarm_port = iprot.readI16();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.LIST:
          self.c_id_list = []
          (_etype66, _size63) = iprot.readListBegin()
          for _i67 in range(_size63):
            _elem68 = iprot.readI32();
            self.c_id_list.append(_elem68)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.success_flag = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('alarm')
    if self.msg_type is not None:
      oprot.writeFieldBegin('msg_type', TType.BYTE, 1)
      oprot.writeByte(self.msg_type)
      oprot.writeFieldEnd()
    if self.alarm_id is not None:
      oprot.writeFieldBegin('alarm_id', TType.I32, 2)
      oprot.writeI32(self.alarm_id)
      oprot.writeFieldEnd()
    if self.alarm_ip is not None:
      oprot.writeFieldBegin('alarm_ip', TType.STRING, 3)
      oprot.writeString(self.alarm_ip)
      oprot.writeFieldEnd()
    if self.alarm_port is not None:
      oprot.writeFieldBegin('alarm_port', TType.I16, 4)
      oprot.writeI16(self.alarm_port)
      oprot.writeFieldEnd()
    if self.c_id_list is not None:
      oprot.writeFieldBegin('c_id_list', TType.LIST, 5)
      oprot.writeListBegin(TType.I32, len(self.c_id_list))
      for iter69 in self.c_id_list:
        oprot.writeI32(iter69)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.success_flag is not None:
      oprot.writeFieldBegin('success_flag', TType.I32, 6)
      oprot.writeI32(self.success_flag)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.msg_type)
    value = (value * 31) ^ hash(self.alarm_id)
    value = (value * 31) ^ hash(self.alarm_ip)
    value = (value * 31) ^ hash(self.alarm_port)
    value = (value * 31) ^ hash(self.c_id_list)
    value = (value * 31) ^ hash(self.success_flag)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
